"""empty message

Revision ID: 192fbdfe1c7b
Revises: 753a9a3b27fa
Create Date: 2024-01-16 19:41:39.075734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192fbdfe1c7b'
down_revision = '753a9a3b27fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
